[package]
name = "lexer"
version = "0.1.0"
authors = ["ChiangYintso <392711804@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.2.1"